show tables;

--ÍNDICES DE TABLAS

--1. TABLA ADUANA

SHOW INDEX FROM aduana;

--2. TABLA ARANCEL

SHOW INDEX FROM arancel;

--3. TABLA BITACORA

SHOW INDEX FROM bitacora;

--4. TABLA CATEGORIAS_PRODUCTOS_REL

SHOW INDEX FROM categorias_productos_rel;

--5. TABLA CATEGORIA_EMBALAJE

SHOW INDEX FROM categoria_embalaje;

--6. TABLA CATEGORIA_PRODUCTOS

SHOW INDEX FROM categoria_productos;

--7. TABLA CLIENTE

SHOW INDEX FROM cliente;

--8. TABLA CORREO_ELECTRONICO

SHOW INDEX FROM correo_electronico;

--9. TABLA ESTADO_OPEADUANERA

SHOW INDEX FROM estado_opeaduanera;

--10. TABLA ESTADO_PAGO

SHOW INDEX FROM estado_pago;

--11. TABLA FACTURA

SHOW INDEX FROM factura;

--12. TABLA INCIDENCIA

SHOW INDEX FROM incidencia;

--13. TABLA INSPECCION

SHOW INDEX FROM inspeccion;

--14. TABLA INSPECCION_INSPECTOR

SHOW INDEX FROM inspeccion_inspector;

--15. TABLA INSPECTOR_ADUANERO

SHOW INDEX FROM inspector_aduanero;

--16. TABLA OPERACION_ADUANERA

SHOW INDEX FROM operacion_aduanera;

--17. TABLA PAGO

SHOW INDEX FROM pago;

--18. TABLA PAQUETE

SHOW INDEX FROM paquete;

--19. TABLA PEDIMENTO

SHOW INDEX FROM pedimento;

--20. TABLA PERMISO

SHOW INDEX FROM permiso;

--21. TABLA PRODUCTO

SHOW INDEX FROM producto;

--22. TABLA REGIMEN_ADUANERO

SHOW INDEX FROM regimen_aduanero;

--23. TABLA SANCION

SHOW INDEX FROM sancion;

--24. TABLA SEGUNDA_INSPECCION

SHOW INDEX FROM segunda_inspeccion;

--25. TABLA SEMAFORO_FISCAL

SHOW INDEX FROM semaforo_fiscal;

--26. TABLA TELEFONO

SHOW INDEX FROM telefono;

--27. TABLA TIPO_ARANCEL

SHOW INDEX FROM tipo_arancel;

--28. TABLA TIPO_EMBALAJE

SHOW INDEX FROM tipo_embalaje;

--29. TABLA TIPO_EXPORTACIONES

SHOW INDEX FROM tipo_exportaciones;

--30. TABLA TIPO_IMPORTACIONES

SHOW INDEX FROM tipo_importaciones;

--31. TABLA TIPO_PERMISO

SHOW INDEX FROM tipo_permiso;

--32. TABLA USUARIO

SHOW INDEX FROM usuario;