# Generated by Django 6.0.6 on 2026-06-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aduana',
            fields=[
                ('codigo', models.AutoField(db_column='codigo', primary_key=True, serialize=False)),
                ('ciudad', models.CharField(db_column='ciudad', max_length=60)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
            ],
            options={
                'verbose_name': 'Aduana',
                'verbose_name_plural': 'Aduanas',
                'db_table': 'aduana',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Arancel',
            fields=[
                ('numero', models.AutoField(db_column='numero', primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(db_column='subtotal', decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=200, null=True)),
                ('IGI', models.DecimalField(db_column='IGI', decimal_places=2, max_digits=5)),
                ('tasa_interes', models.DecimalField(db_column='tasa_interes', decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Arancel',
                'verbose_name_plural': 'Aranceles',
                'db_table': 'arancel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('numero', models.AutoField(db_column='numero', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=250)),
                ('fecha', models.DateField(db_column='fecha')),
                ('hora', models.TimeField(db_column='hora')),
            ],
            options={
                'verbose_name': 'Bitácora',
                'verbose_name_plural': 'Bitácoras',
                'db_table': 'bitacora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaProductos',
            fields=[
                ('numero', models.AutoField(db_column='numero', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Categoría de productos',
                'verbose_name_plural': 'Categorías de productos',
                'db_table': 'categoria_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriasProductosRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Categoría - Producto',
                'verbose_name_plural': 'Categorías - Productos',
                'db_table': 'categorias_productos_rel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('numero', models.AutoField(db_column='numero', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=80)),
                ('primer_apell', models.CharField(blank=True, db_column='primer_apell', max_length=40, null=True)),
                ('seg_apell', models.CharField(blank=True, db_column='seg_apell', max_length=40, null=True)),
                ('tipo_persona', models.CharField(db_column='tipo_persona', max_length=20)),
                ('RFC', models.CharField(db_column='RFC', max_length=13, unique=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorreoElectronico',
            fields=[
                ('numero', models.AutoField(db_column='numero', primary_key=True, serialize=False)),
                ('correoElec', models.CharField(db_column='correoElec', max_length=80)),
            ],
            options={
                'verbose_name': 'Correo electrónico',
                'verbose_name_plural': 'Correos electrónicos',
                'db_table': 'correo_electronico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPago',
            fields=[
                ('codigo', models.AutoField(db_column='codigo', primary_key=True, serialize=False)),
                ('concepto', models.CharField(db_column='concepto', max_length=100)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Estado de pago',
                'verbose_name_plural': 'Estados de pago',
                'db_table': 'estado_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('codigo', models.AutoField(db_column='codigo', primary_key=True, serialize=False)),
                ('IVA', models.DecimalField(db_column='IVA', decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(db_column='subtotal', decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(db_column='total', decimal_places=2, max_digits=12)),
                ('folio_fiscal', models.CharField(db_column='folio_fiscal', max_length=50, unique=True)),
                ('fecha_factura', models.DateField(db_column='fecha_factura')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('codigo', models.AutoField(db_column='codigo', primary_key=True, serialize=False)),
                ('gravedad', models.CharField(db_column='gravedad', max_length=30)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=250)),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'db_table': 'incidencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('numero', models.AutoField(db_column='numero', primary_key=True, serialize=False)),
                ('fecha_inspeccion', models.DateField(db_column='fecha_inspeccion')),
                ('hora_inicio', models.TimeField(db_column='hora_inicio')),
                ('resultado', models.CharField(blank=True, db_column='resultado', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Inspección',
                'verbose_name_plural': 'Inspecciones',
                'db_table': 'inspeccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InspeccionInspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(blank=True, db_column='observaciones', max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Inspección - Inspector',
                'verbose_name_plural': 'Inspecciones - Inspectores',
                'db_table': 'inspeccion_inspector',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InspectorAduanero',
            fields=[
                ('matricula', models.CharField(db_column='matricula', max_length=20, primary_key=True, serialize=False)),
                ('no_gafete', models.CharField(db_column='no_gafete', max_length=25, unique=True)),
                ('nombre_pila', models.CharField(db_column='nombre_pila', max_length=40)),
                ('primer_apell', models.CharField(db_column='primer_apell', max_length=40)),
                ('seg_apell', models.CharField(blank=True, db_column='seg_apell', max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'Inspector aduanero',
                'verbose_name_plural': 'Inspectores aduaneros',
                'db_table': 'inspector_aduanero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OperacionAduanera',
            fields=[
                ('ID_operacion', models.AutoField(db_column='ID_operacion', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(db_column='fecha_inicio')),
                ('fecha_final', models.DateField(blank=True, db_column='fecha_final', null=True)),
                ('tipo_operacion', models.CharField(db_column='tipo_operacion', max_length=20)),
            ],
            options={
                'verbose_name': 'Operación aduanera',
                'verbose_name_plural': 'Operaciones aduaneras',
                'db_table': 'operacion_aduanera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('no_transaccion', models.CharField(db_column='no_transaccion', max_length=50, primary_key=True, serialize=False)),
                ('numero_pago', models.IntegerField(db_column='numero_pago')),
                ('concepto', models.CharField(db_column='concepto', max_length=100)),
                ('saldo_final', models.DecimalField(db_column='saldo_final', decimal_places=2, max_digits=12)),
                ('monto', models.DecimalField(db_column='monto', decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateField(db_column='fecha_pago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('codigo', models.AutoField(db_column='codigo', primary_key=True, serialize=False)),
                ('peso', models.DecimalField(db_column='peso', decimal_places=2, max_digits=10)),
                ('tipo_embalaje', models.CharField(db_column='tipo_embalaje', max_length=30)),
                ('dimensions', models.CharField(blank=True, db_column='dimensions', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Paquete',
                'verbose_name_plural': 'Paquetes',
                'db_table': 'paquete',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedimento',
            fields=[
                ('numero_pedimento', models.CharField(db_column='numero_pedimento', max_length=30, primary_key=True, serialize=False)),
                ('clave_pedimento', models.CharField(db_column='clave_pedimento', max_length=10)),
                ('fecha_registro', models.DateField(db_column='fecha_registro')),
                ('valor_total', models.DecimalField(db_column='valor_total', decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Pedimento',
                'verbose_name_plural': 'Pedimentos',
                'db_table': 'pedimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('clave_numerica', models.CharField(db_column='clave_numerica', max_length=30, primary_key=True, serialize=False)),
                ('tipo_permiso', models.CharField(db_column='tipo_permiso', max_length=50)),
                ('vigencia', models.DateField(db_column='vigencia')),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permiso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.AutoField(db_column='codigo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=200, null=True)),
                ('peso', models.DecimalField(db_column='peso', decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(db_column='valor_unitario', decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegimenAduanero',
            fields=[
                ('num_regimen', models.AutoField(db_column='num_regimen', primary_key=True, serialize=False)),
                ('clave_oficial', models.CharField(db_column='clave_oficial', max_length=10, unique=True)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=200)),
            ],
            options={
                'verbose_name': 'Régimen aduanero',
                'verbose_name_plural': 'Regímenes aduaneros',
                'db_table': 'regimen_aduanero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('num_sancion', models.AutoField(db_column='num_sancion', primary_key=True, serialize=False)),
                ('monto_multa', models.DecimalField(db_column='monto_multa', decimal_places=2, max_digits=12)),
                ('fundamento_legal', models.CharField(db_column='fundamento_legal', max_length=250)),
            ],
            options={
                'verbose_name': 'Sanción',
                'verbose_name_plural': 'Sanciones',
                'db_table': 'sancion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SegundaInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_revision', models.IntegerField(db_column='ID_revision')),
                ('fecha_inspeccion', models.DateField(db_column='fecha_inspeccion')),
                ('hora_inicio', models.TimeField(db_column='hora_inicio')),
                ('resultado', models.CharField(blank=True, db_column='resultado', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Segunda inspección',
                'verbose_name_plural': 'Segundas inspecciones',
                'db_table': 'segunda_inspeccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SegundaInspeccionInspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(blank=True, db_column='observaciones', max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Segunda inspección - Inspector',
                'verbose_name_plural': 'Segundas inspecciones - Inspectores',
                'db_table': 'segunda_inspeccion_inspector',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SemaforoFiscal',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('hora', models.TimeField(db_column='hora')),
                ('resultado', models.CharField(db_column='resultado', max_length=100)),
            ],
            options={
                'verbose_name': 'Semáforo fiscal',
                'verbose_name_plural': 'Semáforos fiscales',
                'db_table': 'semaforo_fiscal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('numero', models.AutoField(db_column='numero', primary_key=True, serialize=False)),
                ('numTelefono', models.CharField(db_column='numTelefono', max_length=20)),
            ],
            options={
                'verbose_name': 'Teléfono',
                'verbose_name_plural': 'Teléfonos',
                'db_table': 'telefono',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoArancel',
            fields=[
                ('numero', models.AutoField(db_column='numero', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=200, null=True)),
                ('fecha_actualizacion', models.DateField(db_column='fecha_actualizacion')),
            ],
            options={
                'verbose_name': 'Tipo de arancel',
                'verbose_name_plural': 'Tipos de arancel',
                'db_table': 'tipo_arancel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoExportaciones',
            fields=[
                ('tipo_exportacion', models.AutoField(db_column='tipo_exportacion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de exportación',
                'verbose_name_plural': 'Tipos de exportación',
                'db_table': 'tipo_exportaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoImportaciones',
            fields=[
                ('tipo_importacion', models.AutoField(db_column='tipo_importacion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de importación',
                'verbose_name_plural': 'Tipos de importación',
                'db_table': 'tipo_importaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPermiso',
            fields=[
                ('id_tipo_permiso', models.AutoField(db_column='id_tipo_permiso', primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='tipo', max_length=50)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de permiso',
                'verbose_name_plural': 'Tipos de permiso',
                'db_table': 'tipo_permiso',
                'managed': False,
            },
        ),
    ]
