# Generated by Django 6.0.6 on 2026-07-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_cliente_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEmbalaje',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Categoría - Embalaje',
                'verbose_name_plural': 'Categorías - Embalajes',
                'db_table': 'categoria_embalaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoOpeAduanera',
            fields=[
                ('codigo', models.AutoField(db_column='codigo', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=100)),
            ],
            options={
                'db_table': 'estado_opeaduanera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEmbalaje',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50, unique=True)),
                ('peso_maximo', models.DecimalField(db_column='peso_maximo', decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de embalaje',
                'verbose_name_plural': 'Tipos de embalaje',
                'db_table': 'tipo_embalaje',
                'managed': False,
            },
        ),
    ]
