from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('operaciones/', views.operaciones_view, name='operaciones'),
    path('operaciones/nueva/', views.operacion_nueva_view,      name='operacion_nueva'),
    path('operaciones/<int:pk>/', views.operacion_detalle_view,    name='operacion_detalle'),
    path('operaciones/<int:pk>/pedimento/', views.operacion_pedimento_view,  name='operacion_pedimento'),
    path('pedimentos/', views.pedimentos_view, name='pedimentos'),
    path('pedimentos/<int:operacion_id>/', views.pedimento_detalle_view, name='pedimento_detalle'),
    path('clientes/', views.clientes_view, name='clientes'),
    path('api/categoria/<int:pk>/productos/', views.api_categoria_productos, name='api_categoria_productos'),
    path('api/cliente/<int:pk>/', views.api_cliente_detalle, name='api_cliente_detalle'),
    path('api/cliente/<int:pk>/permiso/<str:clave>/eliminar/', views.api_permiso_eliminar, name='api_permiso_eliminar'),
    path('aduanas/', views.aduanas_view, name='aduanas'),
    path('aduanas/<int:codigo>/detalle/', views.detalle_aduana, name="detalle_aduana"),
    path('aduanas/<int:codigo>/editar/', views.editar_aduana, name='editar_aduana'),
    path('aduanas/<int:codigo>/cambiar-estado/', views.cambiar_estado_aduana, name='cambiar_estado_aduana'),
    path('categorias/', views.categorias_view, name='categorias'),
    path('bitacora/', views.bitacora_view, name='bitacora'),
    path('api/operacion/', views.api_datos_operacion,  name='api_operacion'),
    path('api/pago/crear/', views.pago_crear_view, name='api_pago_crear'),
    path('api/pedimento/diferir-pago/', views.diferir_pago_view, name='api_diferir_pago'),
    path('api/factura/crear/', views.factura_crear_view, name='api_factura_crear'),
    path('api/factura/<int:codigo>/pdf/', views.factura_pdf_view, name='api_factura_pdf'),
    path('pagos/', views.pagos_view, name='pagos'),
    path('facturas/', views.facturas_view, name='facturas'),
    path('permisos/', views.permisos_view, name='permisos'),
    path('usuarios/', views.usuarios_view, name='usuarios'),
    path('perfilusuario/', views.perfilusuario_view, name='perfilusuario'),
    path('semaforofiscal/', views.semaforofiscal_view, name='semaforo_fiscal'),
    path('inspecciones/', views.inspecciones_view, name='inspecciones'),
    path('inspecciones/<int:pk>/revisar/', views.inspeccion_revisar_view, name='inspeccion_revisar'),
    path('inspecciones/<int:pk>/incidencia/', views.inspeccion_incidencia_view, name='inspeccion_incidencia'),
    path('inspecciones/<int:pk>/detalle/', views.inspeccion_admin_detalle_view, name='inspeccion_admin_detalle'),
    path('api/inspeccion/<int:pk>/resultado/', views.api_inspeccion_resultado, name='api_inspeccion_resultado'),
    path('api/inspeccion/<int:pk>/checklist/', views.api_inspeccion_checklist, name='api_inspeccion_checklist'),
    path('api/inspeccion/<int:pk>/incidencias/', views.api_inspeccion_incidencias, name='api_inspeccion_incidencias'),
    path('api/incidencia/<int:pk>/sancion/', views.api_incidencia_sancion, name='api_incidencia_sancion'),
    path('api/inspeccion/<int:pk>/enviar-segunda/', views.api_enviar_segunda, name='api_enviar_segunda'),
    path('sanciones/', views.sanciones_view, name='sanciones'),
    path('sanciones/<int:pk>/', views.sancion_detalle_view, name='sancion_detalle'),
    path('sanciones/<int:pk>/pagar/', views.multa_pagar_view, name='multa_pagar'),
    path('paquetes/', views.paquetes_view, name='paquetes'),
    path('paquetes/<int:pk>/', views.paquete_detalle_view, name='paquete_detalle'),
    path('paquetes/<int:pk>/eliminar/', views.paquete_eliminar_view, name='paquete_eliminar'),
    path('api/paquetes/<int:paq_pk>/productos/<int:prod_pk>/eliminar/', views.api_producto_eliminar, name='api_producto_eliminar'),
]